CREATE TABLE CIUDADANO(
    numPasaporte VARCHAR(16),
    CONSTRAINT PK_CIUDADANO PRIMARY KEY (numPasaporte),
    CONSTRAINT FK_CIUDADANO_PERSONA FOREIGN KEY (numPasaporte) REFERENCES PERSONA(numPasaporte)
        ON DELETE CASCADE
);