CREATE TABLE CODIGO_CIVIL(
    id INT UNSIGNED AUTO_INCREMENT,
    idPais INT UNSIGNED NOT NULL,
    CONSTRAINT PK_CODIGO_CIVIL PRIMARY KEY (id),
    CONSTRAINT FK_CODIGO_CIVIL_PAIS FOREIGN KEY (idPais) REFERENCES PAIS(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT UK_CODIGO_CIVIL_NOMBRE_PAIS UNIQUE KEY (idPais)
);