CREATE TABLE CONGRESO(
    id INT UNSIGNED AUTO_INCREMENT,
    idPais INT UNSIGNED NOT NULL,
    CONSTRAINT PK_CONGRESO PRIMARY KEY (id),
    CONSTRAINT FK_CONGRESO_PAIS FOREIGN KEY (idPais) REFERENCES PAIS(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT UK_CONGRESO_NOMBRE_PAIS UNIQUE KEY (idPais)
);