CREATE TABLE DESAROLLAR (
    idPropuesta INT UNSIGNED,
    idLey INT UNSIGNED,
    CONSTRAINT PK_DESARROLLAR PRIMARY KEY (idPropuesta, idLey),
    CONSTRAINT FK_DESARROLLAR_PROPUESTA FOREIGN KEY (idPropuesta) REFERENCES PROPUESTA(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT FK_DESARROLLAR_LEY FOREIGN KEY (idLey) REFERENCES LEY(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);