CREATE TABLE PROPUESTA(
    id INT UNSIGNED AUTO_INCREMENT,
    titulo VARCHAR(100) NOT NULL,
    descripcion VARCHAR(2000) NOT NULL,
    fechaExpiracion DATE,
    estado ENUM('ACEPTACION', 'PUBLICACION', 'VOTACION', 'TERMINADA') NOT NULL,
    idCongreso INT UNSIGNED NOT NULL,
    numPasaportePolitico VARCHAR(16) NOT NULL,
    fechaProsicion DATE NOT NULL,
    fechaAceptacion DATE,
    fechaPublicacion DATE,
    CONSTRAINT PK_PROPUESTA PRIMARY KEY (id),
    CONSTRAINT FK_PROPUESTA_CONGRESO FOREIGN KEY (idCongreso) REFERENCES CONGRESO(id),
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
    CONSTRAINT FK_PROPUESTA_POLITICO FOREIGN KEY (numPasaportePolitico) REFERENCES POLITICO(numPasaporte),
        ON DELETE SET NULL
        ON UPDATE CASCADE
);