CREATE TABLE DESAROLLAR (
    idPropuesta INT,
    idLey INT,

    CONSTRAINT PK_PROPUESTA PRIMARY KEY (idPropuesta),
    CONSTRAINT FK_PROPUESTA FOREIGN KEY (idPropuesta),
    CONSTRAINT PK_LEY PRIMARY KEY (idLey),
    CONSTRAINT FK_LEY FOREIGN KEY (idLey)

);