CREATE TABLE CONGRESO(
    id INT UNSIGNED AUTO_INCREMENT,
    nombrePais VARCHAR(64),
    CONSTRAINT PK_CONGRESO PRIMARY KEY (id),
    CONSTRAINT FK_CONGRESO_PAIS FOREIGN KEY (nombrePais) REFERENCES PAIS(nombre)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
);