CREATE TABLE CONGRESO(
    id INT UNSIGNED AUTO_INCREMENT,
    nombrePais VARCHAR(64) NOT NULL,
    CONSTRAINT PK_CONGRESO PRIMARY KEY (id),
    CONSTRAINT FK_CONGRESO_PAIS FOREIGN KEY (nombrePais) REFERENCES PAIS(nombre)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
    CONSTRAINT UK_CONGRESO_NOMBRE_PAIS UNIQUE KEY (nombrePais);
);